package:
  version: {% raw %} "{{ PROJECT_VERSION }}" {% endraw %}
  name: '{{cookiecutter.project_name}}'

source:
  path: ../../

build:
  number: 0
  string: {% raw %} py{{ CONDA_PY }}_0 {% endraw %}
  script: python setup.py install

requirements:
  run:
    - python
    - numpy
    - nose
    - {{cookiecutter.project_name}}
  build:
    - python
    - numpy
    - nose
    - setuptools
    - cython >=0.24.1
    - {% raw %} {{ compiler('c') }} {% endraw %}
    - {% raw %} {{ compiler('cxx') }} {% endraw %}
    - {{cookiecutter.project_name}}

about:
  dev_url: https://github.com/{{cookiecutter.project_org}}/{{cookiecutter.project_name}}
  description: {{cookiecutter.description}} 
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  home: https://github.com/{{cookiecutter.project_org}}/{{cookiecutter.project_name}}
  license_file: LICENSE.txt
  doc_url: https://github.com/{{cookiecutter.project_org}}/{{cookiecutter.project_name}}

extra:
  recipe-maintainers: {{cookiecutter.author}} <{{cookiecutter.email}}>
